# filename:.travis.yml
dist: bionic
sudo: false
notifications:
email: false
env:
before_script:
- export TZ=Asia/Shanghai
script:
- mkdir -p $TRAVIS_BUILD_DIR/output
- mkdir -p $TRAVIS_BUILD_DIR/tmp
# dnsmasq-china-list
- wget -N --no-check-certificate -O ./output/dnsmasq_whitelist_accelerated-domains.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
- wget -N --no-check-certificate -O ./output/dnsmasq_whitelist_bogus-nxdomain.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/bogus-nxdomain.china.conf
- wget -N --no-check-certificate -O ./output/dnsmasq_whitelist_apple.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf

- wget -N --no-check-certificate -O ./output/dns_whitelist_accelerated-domains.china.rsc https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
- wget -N --no-check-certificate -O ./output/dns_whitelist_apple.china.rsc https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf
# sed 可以用行为单位进行部分数据的查找与替换
# sed 's/要被取代的字串/新的字串/g'
- sed -i 's/114.114.114.114/223.5.5.5/g' ./output/dnsmasq_whitelist_accelerated-domains.china.conf
- sed -i 's/114.114.114.114/223.5.5.5/g' ./output/dnsmasq_whitelist_apple.china.conf

- sed -i 's/server=///g' ./output/dns_whitelist_apple.china.rsc
- sed -i 's//114.114.114.114//g' ./output/dns_whitelist_apple.china.rsc
- sed -i 's/\./\\\\./g' ./output/dns_whitelist_apple.china.rsc
- sed -i 's/^/add regexp="(^|(.*\\\\.))&/g' ./output/dns_whitelist_apple.china.rsc
- sed -i 's/$/&\\$" type=FWD forward-to=$dnsCN comment="GFWListDomain"/g' ./output/dns_whitelist_apple.china.rsc
# 
- wget -N --no-check-certificate -O ./tmp/gfwlist2dnsmasq.sh https://raw.githubusercontent.com/cokebar/gfwlist2dnsmasq/master/gfwlist2dnsmasq.sh
- chmod +x ./tmp/gfwlist2dnsmasq.sh
- ./tmp/gfwlist2dnsmasq.sh -d 192.168.20.1 -p 53 -o ./output/dnsmasq_gfwlist_192.168.20.1.conf
- ./tmp/gfwlist2dnsmasq.sh -d 192.168.17.1 -p 53 -o ./output/dnsmasq_gfwlist_192.168.17.1.conf
- ./tmp/gfwlist2dnsmasq.sh -l -o ./output/dns_gfwlist_domain.rsc
- sed -i 's/\./\\\\./g' ./output/dns_gfwlist_domain.rsc
- sed -i 's/^/add regexp="(^|(.*\\\\.))&/g' ./output/dns_gfwlist_domain.rsc
- sed -i 's/$/&\\$" type=FWD forward-to=$dnsGFW comment="GFWListDomain"/g' ./output/dns_gfwlist_domain.rsc
- sed -i '1 i:global dnsGFW' ./output/dns_gfwlist_domain.rsc
- sed -i '2 i/ip dns static remove [/ip dns static find comment="GFWListDomain"]' ./output/dns_gfwlist_domain.rsc
- sed -i '3 i/ip dns static' ./output/dns_gfwlist_domain.rsc
- DATE_TIME=$(date "+%Y-%m-%d %H:%M:%S")
- cd /tmp/
- git clone https://${GIT_USER}:${TOKEN}@github.com/${GIT_USER}/${REPO}.git --branch gh-pages --single-branch gh-pages > /dev/null 2>&1 || exit 1
- cd gh-pages || exit 1
- git config user.name "secondline"
- git config user.email "secondline@hotmail.com"
- git rm dnsmasq_accelerated-domains.china.conf
- git rm dnsmasq_bogus-nxdomain.china.conf
- git rm dnsmasq_apple.china.conf
- git rm dns_gfwlist_domain.rsc
- git rm dnsmasq_gfwlist_192.168.20.1.conf
- git rm dnsmasq_gfwlist_192.168.17.1.conf
- git commit -m "Remove dns_gfwlist_domain.rsc && dnsmasq_gfwlist.conf"
- cp $TRAVIS_BUILD_DIR/output/* .
- git add -A
- git commit -a -m "Configuration Files Generated on [$DATE_TIME]"
- git push -fq origin gh-pages > /dev/null 2>&1 || exit 1
- echo -e "Uploaded files to gh-pages\n"
